### ISSUE TITLE
加载burp报错

### ISSUE THREAD

**Issue by userbalck** [c0r1/BypassPro#2]
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at burp.cvr.a(Unknown Source)
	at burp.cvr.<init>(Unknown Source)
	at burp.cru.a(Unknown Source)
	at burp.av0.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

可否 发布个1.8版本

**Comment by c0r1** [comment]
用的 Burp 是啥版本啊，试试新版 burp 嘞

**Comment by userbalck** [comment]
用的是2022-3.7 老版本了。新版本没有，应该是jdk版本问题，需要一个1.8 版本的

**Comment by c0r1** [comment]
插件用的 2023 年后新版 Burp 才支持的 API 开发，目前没精力维护新老两套 API 哈。师傅可以用原版插件，或者装个新版 Burp

**Comment by c0r1** [comment]
和 JDK 编译版本没关系的
